"""allow unknown build years in the catalog

Revision ID: ba7bf50e0399
Revises: b200e3d2fc2d
Create Date: 2026-09-14 20:03:57.417766
"""
from alembic import op
import sqlalchemy as sa


revision = 'ba7bf50e0399'
down_revision = 'b200e3d2fc2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.alter_column('year_from',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.alter_column('year_from',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
