"""record unresolved research notes on a model version

Revision ID: e0b7bb13024d
Revises: ba7bf50e0399
Create Date: 2026-09-14 20:05:50.053829
"""
from alembic import op
import sqlalchemy as sa


revision = 'e0b7bb13024d'
down_revision = 'ba7bf50e0399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caveat', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_column('caveat')

    # ### end Alembic commands ###
