"""initial schema

Revision ID: b200e3d2fc2d
Revises: 
Create Date: 2026-09-14 16:32:22.356544
"""
from alembic import op
import sqlalchemy as sa


revision = 'b200e3d2fc2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boat_classes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_length_m', sa.Float(), nullable=False),
    sa.Column('max_length_m', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('season_curve', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('license_level', sa.Integer(), nullable=False),
    sa.Column('experience_nm', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boat_models',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designer', sa.String(length=255), nullable=False),
    sa.Column('hull_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id', 'slug', name='uq_model_slug')
    )
    op.create_table('charterers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('commission_percent', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('service_partners',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('base_ids', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('prices', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=False),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('beam_m', sa.Float(), nullable=True),
    sa.Column('draft_m', sa.Float(), nullable=True),
    sa.Column('displacement_kg', sa.Integer(), nullable=True),
    sa.Column('sail_area_m2', sa.Float(), nullable=True),
    sa.Column('engine_hp', sa.Integer(), nullable=True),
    sa.Column('headroom_cm', sa.Integer(), nullable=True),
    sa.Column('max_berth_length_cm', sa.Integer(), nullable=True),
    sa.Column('cabins', sa.Integer(), nullable=True),
    sa.Column('berths', sa.Integer(), nullable=True),
    sa.Column('heads', sa.Integer(), nullable=True),
    sa.Column('max_persons', sa.Integer(), nullable=True),
    sa.Column('water_tank_l', sa.Integer(), nullable=True),
    sa.Column('fuel_tank_l', sa.Integer(), nullable=True),
    sa.Column('character', sa.JSON(), nullable=False),
    sa.Column('standard_features', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('model_images', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('verified_on', sa.Date(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['boat_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('charterer_id', sa.String(length=32), nullable=False),
    sa.Column('base_id', sa.String(length=32), nullable=False),
    sa.Column('boat_class_id', sa.String(length=32), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=True),
    sa.Column('variant_ids', sa.JSON(), nullable=False),
    sa.Column('spec_overrides', sa.JSON(), nullable=False),
    sa.Column('spec_sources', sa.JSON(), nullable=False),
    sa.Column('unknown_specs', sa.JSON(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('year_refit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listing_mode', sa.String(length=20), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('beam_m', sa.Float(), nullable=True),
    sa.Column('draft_m', sa.Float(), nullable=True),
    sa.Column('displacement_kg', sa.Integer(), nullable=True),
    sa.Column('sail_area_m2', sa.Float(), nullable=True),
    sa.Column('engine_hp', sa.Integer(), nullable=True),
    sa.Column('cabins', sa.Integer(), nullable=False),
    sa.Column('berths', sa.Integer(), nullable=False),
    sa.Column('max_persons', sa.Integer(), nullable=False),
    sa.Column('heads', sa.Integer(), nullable=False),
    sa.Column('headroom_cm', sa.Integer(), nullable=True),
    sa.Column('max_berth_length_cm', sa.Integer(), nullable=True),
    sa.Column('character', sa.JSON(), nullable=False),
    sa.Column('required_license', sa.Integer(), nullable=False),
    sa.Column('required_experience_nm', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=False),
    sa.Column('allowed_nights', sa.JSON(), nullable=False),
    sa.Column('min_lead_days', sa.Integer(), nullable=False),
    sa.Column('turnaround_days', sa.Integer(), nullable=False),
    sa.Column('changeover_weekdays', sa.JSON(), nullable=False),
    sa.Column('handover_options', sa.JSON(), nullable=False),
    sa.Column('one_way_enabled', sa.Boolean(), nullable=False),
    sa.Column('one_way_base_ids', sa.JSON(), nullable=False),
    sa.Column('one_way_fee_cents', sa.Integer(), nullable=False),
    sa.Column('deposit_cents', sa.Integer(), nullable=False),
    sa.Column('cleaning_fee_cents', sa.Integer(), nullable=False),
    sa.Column('region_restrictions', sa.Text(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('insurance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], ),
    sa.ForeignKeyConstraint(['boat_class_id'], ['boat_classes.id'], ),
    sa.ForeignKeyConstraint(['charterer_id'], ['charterers.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('variant_options',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('draft_m', sa.Float(), nullable=True),
    sa.Column('sail_area_m2', sa.Float(), nullable=True),
    sa.Column('engine_hp', sa.Integer(), nullable=True),
    sa.Column('cabins', sa.Integer(), nullable=True),
    sa.Column('berths', sa.Integer(), nullable=True),
    sa.Column('heads', sa.Integer(), nullable=True),
    sa.Column('max_persons', sa.Integer(), nullable=True),
    sa.Column('headroom_cm', sa.Integer(), nullable=True),
    sa.Column('max_berth_length_cm', sa.Integer(), nullable=True),
    sa.Column('adds_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'kind', 'code', name='uq_variant_code')
    )
    op.create_table('pricing_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('boat_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference_price_cents', sa.Integer(), nullable=False),
    sa.Column('floor_price_cents', sa.Integer(), nullable=False),
    sa.Column('ceiling_price_cents', sa.Integer(), nullable=False),
    sa.Column('target_price_cents', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('max_dead_gap_days', sa.Integer(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boat_id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('boat_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('persons', sa.Integer(), nullable=False),
    sa.Column('pickup_base_id', sa.String(length=32), nullable=True),
    sa.Column('dropoff_base_id', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['dropoff_base_id'], ['bases.id'], ),
    sa.ForeignKeyConstraint(['pickup_base_id'], ['bases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('boat_id', sa.String(length=32), nullable=False),
    sa.Column('quote_id', sa.String(length=32), nullable=False),
    sa.Column('customer_user_id', sa.String(length=32), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('persons', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('pickup_base_id', sa.String(length=32), nullable=True),
    sa.Column('dropoff_base_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('deposit_cents', sa.Integer(), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=False),
    sa.Column('security_deposit_cents', sa.Integer(), nullable=False),
    sa.Column('static_price_cents', sa.Integer(), nullable=False),
    sa.Column('price_breakdown', sa.JSON(), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(), nullable=True),
    sa.Column('balance_due_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('contract', sa.JSON(), nullable=False),
    sa.Column('contract_accepted_customer_at', sa.DateTime(), nullable=True),
    sa.Column('contract_accepted_charterer_at', sa.DateTime(), nullable=True),
    sa.Column('crew_list', sa.JSON(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('handover_confirmed_customer_at', sa.DateTime(), nullable=True),
    sa.Column('return_confirmed_customer_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dropoff_base_id'], ['bases.id'], ),
    sa.ForeignKeyConstraint(['pickup_base_id'], ['bases.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', name='uq_booking_quote'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('availability_blocks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('boat_id', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('block_type', sa.String(length=20), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('start_base_id', sa.String(length=32), nullable=True),
    sa.Column('end_base_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['end_base_id'], ['bases.id'], ),
    sa.ForeignKeyConstraint(['start_base_id'], ['bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_blocks_boat_range', ['boat_id', 'start_date', 'end_date'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_provider_ref'), ['provider_ref'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=False),
    sa.Column('charterer_id', sa.String(length=32), nullable=False),
    sa.Column('gross_cents', sa.Integer(), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=False),
    sa.Column('service_cost_cents', sa.Integer(), nullable=False),
    sa.Column('damage_withheld_cents', sa.Integer(), nullable=False),
    sa.Column('net_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['charterer_id'], ['charterers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=False),
    sa.Column('boat_id', sa.String(length=32), nullable=False),
    sa.Column('charterer_id', sa.String(length=32), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=True),
    sa.Column('author_user_id', sa.String(length=32), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('charter_month', sa.String(length=7), nullable=False),
    sa.Column('rating_model', sa.Integer(), nullable=True),
    sa.Column('rating_condition', sa.Integer(), nullable=True),
    sa.Column('rating_service', sa.Integer(), nullable=True),
    sa.Column('rating_care', sa.Integer(), nullable=True),
    sa.Column('rating_cleanliness', sa.Integer(), nullable=True),
    sa.Column('rating_accuracy', sa.Integer(), nullable=True),
    sa.Column('rating_equipment', sa.Integer(), nullable=True),
    sa.Column('rating_organisation', sa.Integer(), nullable=True),
    sa.Column('rating_handover', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['charterer_id'], ['charterers.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_review_booking')
    )
    op.create_table('service_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=False),
    sa.Column('boat_id', sa.String(length=32), nullable=False),
    sa.Column('partner_id', sa.String(length=32), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['service_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boat_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('boat_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('charter_month', sa.String(length=7), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=True),
    sa.Column('credit', sa.String(length=255), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=True),
    sa.Column('review_id', sa.String(length=32), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boat_images', schema=None) as batch_op:
        batch_op.create_index('ix_boat_images_boat', ['boat_id', 'sort_order'], unique=False)

    op.create_table('damage_cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=False),
    sa.Column('source_order_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('estimated_cents', sa.Integer(), nullable=False),
    sa.Column('withheld_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['source_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('damage_cases')
    with op.batch_alter_table('boat_images', schema=None) as batch_op:
        batch_op.drop_index('ix_boat_images_boat')

    op.drop_table('boat_images')
    op.drop_table('service_orders')
    op.drop_table('reviews')
    op.drop_table('payouts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_ref'))

    op.drop_table('payments')
    with op.batch_alter_table('availability_blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_blocks_boat_range')

    op.drop_table('availability_blocks')
    op.drop_table('bookings')
    op.drop_table('quotes')
    op.drop_table('pricing_policies')
    op.drop_table('variant_options')
    op.drop_table('boats')
    op.drop_table('model_versions')
    op.drop_table('service_partners')
    op.drop_table('charterers')
    op.drop_table('boat_models')
    op.drop_table('bases')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('manufacturers')
    op.drop_table('boat_classes')
    # ### end Alembic commands ###
