"""Demo master catalog for the Baltic fleet.

The figures are a plausible demo set, not verified manufacturer data. `source` says so on every
version, because the specification requires the origin of a measurement to stay visible.
"""

DEMO_SOURCE = "Demo-Datensatz, nicht herstellerverifiziert"

MANUFACTURERS = [
    {"slug": "bavaria", "name": "Bavaria Yachtbau", "country": "DE"},
    {"slug": "dehler", "name": "Dehler", "country": "DE"},
    {"slug": "hanse", "name": "Hanse Yachts", "country": "DE"},
    {"slug": "hallberg-rassy", "name": "Hallberg-Rassy", "country": "SE"},
    {"slug": "jeanneau", "name": "Jeanneau", "country": "FR"},
    {"slug": "beneteau", "name": "Bénéteau", "country": "FR"},
    {"slug": "dufour", "name": "Dufour Yachts", "country": "FR"},
    {"slug": "x-yachts", "name": "X-Yachts", "country": "DK"},
]

# model slug -> (manufacturer, display name, designer, version)
# Variants carry only what they change; everything else is inherited from the version.
MODELS = [
    {
        "manufacturer": "bavaria",
        "slug": "cruiser-33",
        "name": "Cruiser 33",
        "designer": "Farr Yacht Design",
        "version": {
            "name": "Generation 1",
            "year_from": 2015,
            "year_to": 2021,
            "length_m": 9.99,
            "beam_m": 3.42,
            "draft_m": 1.95,
            "displacement_kg": 5500,
            "sail_area_m2": 58,
            "engine_hp": 20,
            "headroom_cm": 190,
            "max_berth_length_cm": 198,
            "cabins": 2,
            "berths": 4,
            "heads": 1,
            "max_persons": 5,
            "water_tank_l": 210,
            "fuel_tank_l": 150,
            "character": ["good_natured"],
            "standard_features": ["plotter", "sprayhood"],
            "description": "Kompakte Fahrtenyacht, einfach zu segeln und leicht zu manövrieren.",
        },
        "variants": [
            {"kind": "layout", "code": "2-kab", "name": "2 Kabinen", "is_default": True},
            {
                "kind": "layout",
                "code": "3-kab",
                "name": "3 Kabinen",
                "cabins": 3,
                "berths": 6,
                "max_persons": 6,
            },
            {"kind": "keel", "code": "standard", "name": "Standardkiel 1,95 m", "is_default": True},
            {
                "kind": "keel",
                "code": "flach",
                "name": "Flachkiel 1,55 m",
                "draft_m": 1.55,
                "adds_features": ["shallow_draft"],
            },
            {"kind": "rig", "code": "standard", "name": "Standardrigg mit Rollfock", "is_default": True},
            {"kind": "engine", "code": "20ps", "name": "20 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "bavaria",
        "slug": "cruiser-34",
        "name": "Cruiser 34",
        "designer": "Farr Yacht Design",
        "version": {
            "name": "Generation 1",
            "year_from": 2016,
            "year_to": 2022,
            "length_m": 9.99,
            "beam_m": 3.42,
            "draft_m": 1.90,
            "displacement_kg": 5700,
            "sail_area_m2": 58,
            "engine_hp": 20,
            "headroom_cm": 192,
            "max_berth_length_cm": 200,
            "cabins": 2,
            "berths": 4,
            "heads": 1,
            "max_persons": 5,
            "water_tank_l": 210,
            "fuel_tank_l": 150,
            "character": ["good_natured"],
            "standard_features": ["plotter", "sprayhood"],
            "description": "Nachfolgerin der Cruiser 33 mit etwas mehr Volumen im Salon.",
        },
        "variants": [
            {"kind": "layout", "code": "2-kab", "name": "2 Kabinen", "is_default": True},
            {"kind": "keel", "code": "standard", "name": "Standardkiel 1,90 m", "is_default": True},
            {
                "kind": "keel",
                "code": "kurzkiel",
                "name": "Kurzkiel 1,45 m",
                "draft_m": 1.45,
                "adds_features": ["shallow_draft"],
            },
            {"kind": "rig", "code": "standard", "name": "Standardrigg", "is_default": True},
            {"kind": "engine", "code": "20ps", "name": "20 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "bavaria",
        "slug": "cruiser-37",
        "name": "Cruiser 37",
        "designer": "Farr Yacht Design",
        "version": {
            "name": "Generation 2",
            "year_from": 2017,
            "year_to": 2022,
            "length_m": 11.30,
            "beam_m": 3.67,
            "draft_m": 1.95,
            "displacement_kg": 7800,
            "sail_area_m2": 76,
            "engine_hp": 29,
            "headroom_cm": 200,
            "max_berth_length_cm": 205,
            "cabins": 2,
            "berths": 4,
            "heads": 1,
            "max_persons": 6,
            "water_tank_l": 360,
            "fuel_tank_l": 210,
            "character": ["good_natured", "comfort"],
            "standard_features": ["plotter", "sprayhood", "autopilot"],
            "description": "Gutmütige Familienyacht mit großem Cockpit und viel Stauraum.",
        },
        "variants": [
            {"kind": "layout", "code": "2-kab", "name": "2 Kabinen", "is_default": True},
            {
                "kind": "layout",
                "code": "3-kab",
                "name": "3 Kabinen",
                "cabins": 3,
                "berths": 6,
                "max_persons": 7,
            },
            {"kind": "keel", "code": "standard", "name": "Standardkiel 1,95 m", "is_default": True},
            {
                "kind": "keel",
                "code": "flach",
                "name": "Flachkiel 1,60 m",
                "draft_m": 1.60,
                "adds_features": ["shallow_draft"],
            },
            {"kind": "rig", "code": "standard", "name": "Standardrigg", "is_default": True},
            {
                "kind": "rig",
                "code": "selbstwende",
                "name": "Selbstwendefock",
                "sail_area_m2": 72,
                "adds_features": ["selftacking_jib"],
            },
            {"kind": "engine", "code": "29ps", "name": "29 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "dehler",
        "slug": "38",
        "name": "38",
        "designer": "Judel/Vrolijk",
        "version": {
            "name": "Generation 1",
            "year_from": 2013,
            "year_to": 2019,
            "length_m": 11.30,
            "beam_m": 3.75,
            "draft_m": 2.00,
            "displacement_kg": 7500,
            "sail_area_m2": 85,
            "engine_hp": 29,
            "headroom_cm": 195,
            "max_berth_length_cm": 200,
            "cabins": 2,
            "berths": 4,
            "heads": 1,
            "max_persons": 6,
            "water_tank_l": 300,
            "fuel_tank_l": 160,
            "character": ["sporty"],
            "standard_features": ["plotter", "autopilot", "sprayhood"],
            "description": "Performance-Cruiser, der sauberen Trimm belohnt.",
        },
        "variants": [
            {
                "kind": "layout",
                "code": "3-kab",
                "name": "3 Kabinen",
                "cabins": 3,
                "berths": 6,
                "is_default": True,
            },
            {"kind": "keel", "code": "standard", "name": "Standardkiel 2,00 m", "is_default": True},
            {"kind": "keel", "code": "tief", "name": "Tiefkiel 2,25 m", "draft_m": 2.25},
            {"kind": "rig", "code": "standard", "name": "Alumast", "is_default": True},
            {
                "kind": "rig",
                "code": "carbon",
                "name": "Carbonmast",
                "sail_area_m2": 89,
                "adds_features": ["carbon_mast", "code0"],
            },
            {"kind": "engine", "code": "29ps", "name": "29 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "hanse",
        "slug": "418",
        "name": "418",
        "designer": "Judel/Vrolijk",
        "version": {
            "name": "Generation 1",
            "year_from": 2016,
            "year_to": 2023,
            "length_m": 12.40,
            "beam_m": 4.17,
            "draft_m": 2.10,
            "displacement_kg": 9900,
            "sail_area_m2": 88,
            "engine_hp": 39,
            "headroom_cm": 205,
            "max_berth_length_cm": 210,
            "cabins": 3,
            "berths": 6,
            "heads": 1,
            "max_persons": 8,
            "water_tank_l": 465,
            "fuel_tank_l": 250,
            "character": ["comfort", "good_natured"],
            "standard_features": ["selftacking_jib", "plotter", "autopilot", "sprayhood"],
            "description": "Breite Fahrtenyacht mit Selbstwendefock und sehr viel Stehhöhe.",
        },
        "variants": [
            {"kind": "layout", "code": "3-kab-1-bad", "name": "3 Kabinen, 1 Bad", "is_default": True},
            {"kind": "layout", "code": "3-kab-2-bad", "name": "3 Kabinen, 2 Bäder", "heads": 2, "berths": 8},
            {"kind": "keel", "code": "standard", "name": "Standardkiel 2,10 m", "is_default": True},
            {
                "kind": "keel",
                "code": "flach",
                "name": "Flachkiel 1,75 m",
                "draft_m": 1.75,
                "adds_features": ["shallow_draft"],
            },
            {"kind": "rig", "code": "selbstwende", "name": "Selbstwendefock", "is_default": True},
            {"kind": "engine", "code": "39ps", "name": "39 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "hallberg-rassy",
        "slug": "40",
        "name": "40",
        "designer": "Germán Frers",
        "version": {
            "name": "Mk II",
            "year_from": 2010,
            "year_to": 2016,
            "length_m": 12.40,
            "beam_m": 3.83,
            "draft_m": 1.95,
            "displacement_kg": 11000,
            "sail_area_m2": 84,
            "engine_hp": 55,
            "headroom_cm": 198,
            "max_berth_length_cm": 205,
            "cabins": 2,
            "berths": 6,
            "heads": 1,
            "max_persons": 6,
            "water_tank_l": 600,
            "fuel_tank_l": 380,
            "character": ["bluewater", "comfort", "classic"],
            "standard_features": ["autopilot", "plotter", "heating", "bowthruster", "hardtop"],
            "description": "Seetüchtige Mittelcockpit-Yacht, ruhig und trocken auch bei Starkwind.",
        },
        "variants": [
            {"kind": "layout", "code": "2-kab", "name": "2 Kabinen, Mittelcockpit", "is_default": True},
            {"kind": "keel", "code": "standard", "name": "Standardkiel 1,95 m", "is_default": True},
            {"kind": "rig", "code": "standard", "name": "Standardrigg", "is_default": True},
            {"kind": "engine", "code": "55ps", "name": "55 PS Welle", "is_default": True},
        ],
    },
    {
        "manufacturer": "jeanneau",
        "slug": "sun-odyssey-349",
        "name": "Sun Odyssey 349",
        "designer": "Marc Lombard",
        "version": {
            "name": "Generation 1",
            "year_from": 2014,
            "year_to": 2022,
            "length_m": 10.34,
            "beam_m": 3.44,
            "draft_m": 1.98,
            "displacement_kg": 5350,
            "sail_area_m2": 60,
            "engine_hp": 21,
            "headroom_cm": 190,
            "max_berth_length_cm": 195,
            "cabins": 2,
            "berths": 4,
            "heads": 1,
            "max_persons": 6,
            "water_tank_l": 200,
            "fuel_tank_l": 130,
            "character": ["good_natured", "sporty"],
            "standard_features": ["plotter", "sprayhood"],
            "description": "Leichtfüßige 34er, die am Ruder Spaß macht und trotzdem verzeiht.",
        },
        "variants": [
            {"kind": "layout", "code": "2-kab", "name": "2 Kabinen", "is_default": True},
            {"kind": "layout", "code": "3-kab", "name": "3 Kabinen", "cabins": 3, "berths": 6},
            {"kind": "keel", "code": "standard", "name": "Standardkiel 1,98 m", "is_default": True},
            {
                "kind": "keel",
                "code": "flach",
                "name": "Flachkiel 1,49 m",
                "draft_m": 1.49,
                "adds_features": ["shallow_draft"],
            },
            {"kind": "rig", "code": "standard", "name": "Standardrigg", "is_default": True},
            {"kind": "engine", "code": "21ps", "name": "21 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "beneteau",
        "slug": "oceanis-46-1",
        "name": "Oceanis 46.1",
        "designer": "Finot-Conq / Nauta Design",
        "version": {
            "name": "Generation 1",
            "year_from": 2018,
            "year_to": None,
            "length_m": 14.60,
            "beam_m": 4.50,
            "draft_m": 2.35,
            "displacement_kg": 10600,
            "sail_area_m2": 105,
            "engine_hp": 57,
            "headroom_cm": 208,
            "max_berth_length_cm": 210,
            "cabins": 3,
            "berths": 6,
            "heads": 2,
            "max_persons": 8,
            "water_tank_l": 640,
            "fuel_tank_l": 400,
            "character": ["comfort"],
            "standard_features": ["bowthruster", "autopilot", "plotter", "sprayhood", "bimini"],
            "description": "Große Fahrtenyacht mit weitem Cockpit, gebaut für Gruppen.",
        },
        "variants": [
            {"kind": "layout", "code": "3-kab", "name": "3 Kabinen, 2 Bäder", "is_default": True},
            {
                "kind": "layout",
                "code": "4-kab",
                "name": "4 Kabinen, 3 Bäder",
                "cabins": 4,
                "berths": 10,
                "heads": 3,
                "max_persons": 10,
            },
            {"kind": "keel", "code": "standard", "name": "Standardkiel 2,35 m", "is_default": True},
            {
                "kind": "keel",
                "code": "flach",
                "name": "Flachkiel 1,85 m",
                "draft_m": 1.85,
                "adds_features": ["shallow_draft"],
            },
            {"kind": "rig", "code": "standard", "name": "Standardrigg", "is_default": True},
            {"kind": "rig", "code": "performance", "name": "Performance-Rigg", "sail_area_m2": 118},
            {"kind": "engine", "code": "57ps", "name": "57 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "dufour",
        "slug": "390",
        "name": "390",
        "designer": "Umberto Felci",
        "version": {
            "name": "Grand Large",
            "year_from": 2018,
            "year_to": None,
            "length_m": 11.93,
            "beam_m": 3.99,
            "draft_m": 1.90,
            "displacement_kg": 8000,
            "sail_area_m2": 78,
            "engine_hp": 40,
            "headroom_cm": 200,
            "max_berth_length_cm": 205,
            "cabins": 2,
            "berths": 4,
            "heads": 1,
            "max_persons": 6,
            "water_tank_l": 440,
            "fuel_tank_l": 200,
            "character": ["comfort", "good_natured"],
            "standard_features": ["plotter", "autopilot", "sprayhood", "outdoor_galley"],
            "description": "Fahrtenyacht mit Außenküche und großer Badeplattform.",
        },
        "variants": [
            {"kind": "layout", "code": "2-kab", "name": "2 Kabinen", "is_default": True},
            {
                "kind": "layout",
                "code": "3-kab",
                "name": "3 Kabinen, 2 Bäder",
                "cabins": 3,
                "berths": 6,
                "heads": 2,
                "max_persons": 8,
            },
            {"kind": "keel", "code": "standard", "name": "Standardkiel 1,90 m", "is_default": True},
            {
                "kind": "keel",
                "code": "flach",
                "name": "Flachkiel 1,70 m",
                "draft_m": 1.70,
                "adds_features": ["shallow_draft"],
            },
            {"kind": "rig", "code": "standard", "name": "Standardrigg", "is_default": True},
            {"kind": "engine", "code": "40ps", "name": "40 PS Saildrive", "is_default": True},
        ],
    },
    {
        "manufacturer": "x-yachts",
        "slug": "x4-3",
        "name": "X4³",
        "designer": "Niels Jeppesen",
        "version": {
            "name": "Generation 1",
            "year_from": 2017,
            "year_to": None,
            "length_m": 12.90,
            "beam_m": 3.95,
            "draft_m": 2.20,
            "displacement_kg": 9300,
            "sail_area_m2": 98,
            "engine_hp": 40,
            "headroom_cm": 196,
            "max_berth_length_cm": 200,
            "cabins": 2,
            "berths": 4,
            "heads": 1,
            "max_persons": 6,
            "water_tank_l": 360,
            "fuel_tank_l": 210,
            "character": ["sporty", "bluewater"],
            "standard_features": ["autopilot", "plotter", "sprayhood", "heating"],
            "description": "Performance-Cruiser mit Stahlrahmen, schnell und dabei seefest.",
        },
        "variants": [
            {
                "kind": "layout",
                "code": "3-kab",
                "name": "3 Kabinen, 2 Bäder",
                "cabins": 3,
                "berths": 6,
                "heads": 2,
                "is_default": True,
            },
            {"kind": "keel", "code": "standard", "name": "Standardkiel 2,20 m", "is_default": True},
            {"kind": "keel", "code": "tief", "name": "Tiefkiel 2,45 m", "draft_m": 2.45},
            {
                "kind": "rig",
                "code": "carbon",
                "name": "Carbonmast",
                "is_default": True,
                "adds_features": ["carbon_mast", "code0"],
            },
            {"kind": "engine", "code": "40ps", "name": "40 PS Saildrive", "is_default": True},
        ],
    },
]

# Existing demo boats -> the catalog entry they were built from.
BOAT_CATALOG_LINK = {
    "nordwind": ("bavaria", "cruiser-37", ["3-kab", "standard", "standard", "29ps"]),
    "sturmvogel": ("dehler", "38", ["3-kab", "standard", "carbon", "29ps"]),
    "foerdeperle": ("hanse", "418", ["3-kab-2-bad", "standard", "selbstwende", "39ps"]),
    "kleine-freiheit": ("bavaria", "cruiser-33", ["2-kab", "standard", "standard", "20ps"]),
    "jomsborg": ("hallberg-rassy", "40", ["2-kab", "standard", "standard", "55ps"]),
    "windsbraut": ("jeanneau", "sun-odyssey-349", ["3-kab", "standard", "standard", "21ps"]),
    "baltic-star": ("beneteau", "oceanis-46-1", ["4-kab", "standard", "standard", "57ps"]),
    "hiddensee": ("bavaria", "cruiser-34", ["2-kab", "kurzkiel", "standard", "20ps"]),
    "boddenlaeufer": ("dufour", "390", ["3-kab", "flach", "standard", "40ps"]),
    "kap-arkona": ("x-yachts", "x4-3", ["3-kab", "standard", "carbon", "40ps"]),
}

# Demo reviews so the boat page shows something. Keyed by boat slug.
DEMO_REVIEWS = [
    {
        "boat": "nordwind",
        "author": "Familie Brandt",
        "month_offset": -4,
        "ratings": {
            "rating_model": 5,
            "rating_condition": 5,
            "rating_service": 5,
            "rating_care": 5,
            "rating_cleanliness": 5,
            "rating_accuracy": 5,
            "rating_equipment": 4,
            "rating_organisation": 5,
            "rating_handover": 5,
        },
        "title": "Genau das Boot für unsere erste eigene Woche",
        "body": "Sehr gutmütig zu segeln, im Salon konnte unser 1,90er Sohn aufrecht stehen. "
        "Die Übergabe war gründlich, alles war sauber und vollgetankt.",
    },
    {
        "boat": "nordwind",
        "author": "Jan Petersen",
        "month_offset": -11,
        "ratings": {
            "rating_model": 4,
            "rating_condition": 4,
            "rating_service": 5,
            "rating_care": 4,
            "rating_cleanliness": 5,
            "rating_accuracy": 5,
            "rating_equipment": 4,
            "rating_organisation": 5,
            "rating_handover": 4,
        },
        "title": "Solide Fahrtenyacht, ehrliche Beschreibung",
        "body": "Das Boot war exakt so wie im Inserat. Das Großsegel hat ein paar Jahre auf dem "
        "Buckel, stört beim Fahrtensegeln aber nicht.",
    },
    {
        "boat": "kleine-freiheit",
        "author": "Miriam Kock",
        "month_offset": -6,
        "ratings": {
            "rating_model": 4,
            "rating_condition": 5,
            "rating_service": 4,
            "rating_care": 5,
            "rating_cleanliness": 5,
            "rating_accuracy": 4,
            "rating_equipment": 3,
            "rating_organisation": 4,
            "rating_handover": 4,
        },
        "title": "Handlich zu zweit",
        "body": "Für ein Paar völlig ausreichend und im Hafen leicht zu manövrieren. "
        "Kartenplotter ist älteres Modell, Papierkarte war an Bord.",
    },
    {
        "boat": "baltic-star",
        "author": "Segelclub Travemünde",
        "month_offset": -3,
        "ratings": {
            "rating_model": 5,
            "rating_condition": 4,
            "rating_service": 4,
            "rating_care": 4,
            "rating_cleanliness": 4,
            "rating_accuracy": 5,
            "rating_equipment": 5,
            "rating_organisation": 4,
            "rating_handover": 4,
        },
        "title": "Viel Platz für acht Leute",
        "body": "Die vier Kabinen machen den Unterschied, niemand musste im Salon schlafen. "
        "Tiefgang muss man in den Bodden im Blick behalten.",
    },
]
