"""Demo catalogue for the Baltic Sea. Plain data so it can be replaced by imports later."""

BALTIC_SEASON = {
    1: 0.30,
    2: 0.30,
    3: 0.35,
    4: 0.50,
    5: 0.70,
    6: 0.85,
    7: 1.00,
    8: 1.00,
    9: 0.80,
    10: 0.55,
    11: 0.35,
    12: 0.30,
}

REGIONS = [
    {
        "slug": "westliche-ostsee",
        "name": "Westliche Ostsee",
        "country": "DE",
        "description": "Kieler Förde, Flensburger Förde, dänische Südsee. Kurze Schläge, viele Häfen.",
        "season_curve": BALTIC_SEASON,
    },
    {
        "slug": "ruegen-bodden",
        "name": "Rügen & Bodden",
        "country": "DE",
        "description": "Stralsund, Hiddensee, Greifswalder Bodden. Geschützte Reviere, ideal für Einsteiger.",
        "season_curve": BALTIC_SEASON,
    },
    {
        "slug": "mecklenburg",
        "name": "Mecklenburgische Küste",
        "country": "DE",
        "description": "Rostock/Warnemünde, Wismar, Kühlungsborn. Sprungbrett nach Dänemark.",
        "season_curve": BALTIC_SEASON,
    },
]

BASES = [
    {
        "region": "westliche-ostsee",
        "name": "Marina Heiligenhafen",
        "city": "Heiligenhafen",
        "lat": 54.374,
        "lon": 10.982,
    },
    {"region": "westliche-ostsee", "name": "Sonwik Marina", "city": "Flensburg", "lat": 54.815, "lon": 9.459},
    {
        "region": "westliche-ostsee",
        "name": "Marina Kiel-Schilksee",
        "city": "Kiel",
        "lat": 54.425,
        "lon": 10.170,
    },
    {
        "region": "ruegen-bodden",
        "name": "Citymarina Stralsund",
        "city": "Stralsund",
        "lat": 54.315,
        "lon": 13.096,
    },
    {
        "region": "ruegen-bodden",
        "name": "Marina Breege",
        "city": "Breege/Rügen",
        "lat": 54.620,
        "lon": 13.352,
    },
    {
        "region": "mecklenburg",
        "name": "Hohe Düne",
        "city": "Rostock-Warnemünde",
        "lat": 54.180,
        "lon": 12.100,
    },
]

BOAT_CLASSES = [
    {
        "slug": "small-cruiser",
        "name": "Kleine Fahrtenyacht bis 32 ft",
        "min_length_m": 0,
        "max_length_m": 10.0,
    },
    {"slug": "cruiser-33-37", "name": "Fahrtenyacht 33–37 ft", "min_length_m": 10.0, "max_length_m": 11.5},
    {"slug": "cruiser-38-42", "name": "Fahrtenyacht 38–42 ft", "min_length_m": 11.5, "max_length_m": 13.0},
    {"slug": "cruiser-43-plus", "name": "Fahrtenyacht ab 43 ft", "min_length_m": 13.0, "max_length_m": 99},
]

CHARTERERS = [
    {
        "slug": "ostsee-yachting",
        "name": "Ostsee Yachting Heiligenhafen",
        "email": "charter@ostsee-yachting.example",
        "password": "charter123",
        "commission_percent": 15.0,
        "rating": 4.7,
    },
    {
        "slug": "foerde-charter",
        "name": "Förde Charter Flensburg",
        "email": "info@foerde-charter.example",
        "password": "charter123",
        "commission_percent": 15.0,
        "rating": 4.5,
    },
    {
        "slug": "bodden-segler",
        "name": "Boddensegler Stralsund",
        "email": "moin@boddensegler.example",
        "password": "charter123",
        "commission_percent": 12.0,
        "rating": 4.8,
    },
]

# reference/floor/ceiling are per-night prices in EUR
BOATS = [
    {
        "charterer": "ostsee-yachting",
        "base": "Marina Heiligenhafen",
        "name": "Nordwind",
        "manufacturer": "Bavaria",
        "model": "Cruiser 37",
        "year_built": 2019,
        "length_m": 11.3,
        "beam_m": 3.67,
        "draft_m": 1.95,
        "displacement_kg": 7800,
        "sail_area_m2": 76,
        "engine_hp": 29,
        "cabins": 3,
        "berths": 6,
        "max_persons": 7,
        "heads": 1,
        "headroom_cm": 200,
        "max_berth_length_cm": 205,
        "character": ["good_natured", "comfort"],
        "required_license": 2,
        "required_experience_nm": 0,
        "features": ["bowthruster", "autopilot", "plotter", "sprayhood", "bimini", "heating"],
        "description": "Gutmütige Familienyacht mit viel Platz im Cockpit und Salon. Einfach zu segeln, ideal für Einsteiger und Familien.",
        "min_days": 3,
        "cleaning_fee": 150,
        "deposit": 2500,
        "ref": 290,
        "floor": 170,
        "ceiling": 420,
    },
    {
        "charterer": "ostsee-yachting",
        "base": "Marina Heiligenhafen",
        "name": "Sturmvogel",
        "manufacturer": "Dehler",
        "model": "38",
        "year_built": 2017,
        "length_m": 11.3,
        "beam_m": 3.75,
        "draft_m": 2.0,
        "displacement_kg": 7500,
        "sail_area_m2": 85,
        "engine_hp": 29,
        "cabins": 3,
        "berths": 6,
        "max_persons": 6,
        "heads": 1,
        "headroom_cm": 195,
        "max_berth_length_cm": 200,
        "character": ["sporty"],
        "required_license": 2,
        "required_experience_nm": 500,
        "features": ["autopilot", "plotter", "sprayhood", "code0", "carbon_mast"],
        "description": "Schnelle Performance-Cruiserin für ambitionierte Crews. Belohnt gutes Trimmen, verlangt Aufmerksamkeit.",
        "min_days": 3,
        "cleaning_fee": 150,
        "deposit": 3000,
        "ref": 320,
        "floor": 190,
        "ceiling": 480,
    },
    {
        "charterer": "ostsee-yachting",
        "base": "Marina Kiel-Schilksee",
        "name": "Fördeperle",
        "manufacturer": "Hanse",
        "model": "418",
        "year_built": 2021,
        "length_m": 12.4,
        "beam_m": 4.17,
        "draft_m": 2.1,
        "displacement_kg": 9900,
        "sail_area_m2": 88,
        "engine_hp": 39,
        "cabins": 3,
        "berths": 8,
        "max_persons": 8,
        "heads": 2,
        "headroom_cm": 205,
        "max_berth_length_cm": 210,
        "character": ["comfort", "good_natured"],
        "required_license": 2,
        "required_experience_nm": 300,
        "features": [
            "bowthruster",
            "autopilot",
            "plotter",
            "sprayhood",
            "bimini",
            "heating",
            "selftacking_jib",
            "electric_winch",
        ],
        "description": "Moderne, breite Fahrtenyacht mit Selbstwendefock. Viel Stehhöhe, lange Kojen, zwei Nasszellen.",
        "min_days": 4,
        "cleaning_fee": 180,
        "deposit": 3000,
        "ref": 390,
        "floor": 230,
        "ceiling": 560,
    },
    {
        "charterer": "ostsee-yachting",
        "base": "Marina Kiel-Schilksee",
        "name": "Kleine Freiheit",
        "manufacturer": "Bavaria",
        "model": "Cruiser 33",
        "year_built": 2016,
        "length_m": 9.99,
        "beam_m": 3.42,
        "draft_m": 1.95,
        "displacement_kg": 5500,
        "sail_area_m2": 58,
        "engine_hp": 20,
        "cabins": 2,
        "berths": 4,
        "max_persons": 5,
        "heads": 1,
        "headroom_cm": 190,
        "max_berth_length_cm": 198,
        "character": ["good_natured"],
        "required_license": 2,
        "required_experience_nm": 0,
        "features": ["autopilot", "plotter", "sprayhood"],
        "description": "Kompakt, handlich, günstig. Perfekt für Paare oder kleine Familien und den ersten eigenen Törn.",
        "min_days": 2,
        "cleaning_fee": 100,
        "deposit": 1500,
        "ref": 190,
        "floor": 110,
        "ceiling": 280,
    },
    {
        "charterer": "foerde-charter",
        "base": "Sonwik Marina",
        "name": "Jomsborg",
        "manufacturer": "Hallberg-Rassy",
        "model": "40",
        "year_built": 2012,
        "year_refit": 2022,
        "length_m": 12.4,
        "beam_m": 3.83,
        "draft_m": 1.95,
        "displacement_kg": 11000,
        "sail_area_m2": 84,
        "engine_hp": 55,
        "cabins": 2,
        "berths": 6,
        "max_persons": 6,
        "heads": 1,
        "headroom_cm": 198,
        "max_berth_length_cm": 205,
        "character": ["bluewater", "comfort", "classic"],
        "required_license": 3,
        "required_experience_nm": 1000,
        "features": [
            "bowthruster",
            "autopilot",
            "radar",
            "plotter",
            "hardtop",
            "heating",
            "generator",
            "watermaker",
        ],
        "description": "Seetüchtige Langfahrtyacht mit Mittelcockpit und Hardtop. Ruhig, trocken, sicher, auch bei Starkwind.",
        "min_days": 5,
        "cleaning_fee": 200,
        "deposit": 4000,
        "ref": 450,
        "floor": 260,
        "ceiling": 650,
    },
    {
        "charterer": "foerde-charter",
        "base": "Sonwik Marina",
        "name": "Windsbraut",
        "manufacturer": "Jeanneau",
        "model": "Sun Odyssey 349",
        "year_built": 2020,
        "length_m": 10.34,
        "beam_m": 3.44,
        "draft_m": 1.98,
        "displacement_kg": 5350,
        "sail_area_m2": 60,
        "engine_hp": 21,
        "cabins": 3,
        "berths": 6,
        "max_persons": 6,
        "heads": 1,
        "headroom_cm": 190,
        "max_berth_length_cm": 195,
        "character": ["good_natured", "sporty"],
        "required_license": 2,
        "required_experience_nm": 0,
        "features": ["autopilot", "plotter", "sprayhood", "bimini"],
        "description": "Leichtfüßige 34er mit drei Kabinen. Macht Spaß am Ruder und ist trotzdem gutmütig.",
        "min_days": 3,
        "cleaning_fee": 120,
        "deposit": 2000,
        "ref": 240,
        "floor": 140,
        "ceiling": 350,
    },
    {
        "charterer": "foerde-charter",
        "base": "Sonwik Marina",
        "name": "Baltic Star",
        "manufacturer": "Beneteau",
        "model": "Oceanis 46.1",
        "year_built": 2022,
        "length_m": 14.6,
        "beam_m": 4.5,
        "draft_m": 2.35,
        "displacement_kg": 10600,
        "sail_area_m2": 105,
        "engine_hp": 57,
        "cabins": 4,
        "berths": 10,
        "max_persons": 10,
        "heads": 3,
        "headroom_cm": 208,
        "max_berth_length_cm": 210,
        "character": ["comfort"],
        "required_license": 2,
        "required_experience_nm": 800,
        "features": [
            "bowthruster",
            "autopilot",
            "plotter",
            "radar",
            "bimini",
            "sprayhood",
            "heating",
            "electric_winch",
            "generator",
        ],
        "description": "Große, komfortable Yacht für Gruppen und Familienverbände. Vier Kabinen, drei Bäder, riesiges Cockpit.",
        "min_days": 5,
        "cleaning_fee": 250,
        "deposit": 5000,
        "ref": 620,
        "floor": 360,
        "ceiling": 900,
    },
    {
        "charterer": "bodden-segler",
        "base": "Citymarina Stralsund",
        "name": "Hiddensee",
        "manufacturer": "Bavaria",
        "model": "Cruiser 34",
        "year_built": 2018,
        "length_m": 9.99,
        "beam_m": 3.42,
        "draft_m": 1.45,
        "displacement_kg": 5700,
        "sail_area_m2": 58,
        "engine_hp": 20,
        "cabins": 2,
        "berths": 4,
        "max_persons": 5,
        "heads": 1,
        "headroom_cm": 192,
        "max_berth_length_cm": 200,
        "character": ["good_natured"],
        "required_license": 1,
        "required_experience_nm": 0,
        "features": ["autopilot", "plotter", "sprayhood", "shallow_draft"],
        "description": "Flachgehende Bodden-Yacht mit Kurzkiel. Kommt überall hin, verzeiht viel, ideal für Anfänger.",
        "min_days": 2,
        "cleaning_fee": 90,
        "deposit": 1500,
        "ref": 180,
        "floor": 100,
        "ceiling": 270,
    },
    {
        "charterer": "bodden-segler",
        "base": "Citymarina Stralsund",
        "name": "Boddenläufer",
        "manufacturer": "Dufour",
        "model": "390",
        "year_built": 2020,
        "length_m": 11.93,
        "beam_m": 3.99,
        "draft_m": 1.7,
        "displacement_kg": 8000,
        "sail_area_m2": 78,
        "engine_hp": 40,
        "cabins": 3,
        "berths": 6,
        "max_persons": 8,
        "heads": 2,
        "headroom_cm": 200,
        "max_berth_length_cm": 205,
        "character": ["comfort", "good_natured"],
        "required_license": 2,
        "required_experience_nm": 200,
        "features": ["bowthruster", "autopilot", "plotter", "bimini", "sprayhood", "outdoor_galley"],
        "description": "Moderne Fahrtenyacht mit Außenküche und Badeplattform. Viel Komfort für Sommertörns.",
        "min_days": 3,
        "cleaning_fee": 150,
        "deposit": 2500,
        "ref": 330,
        "floor": 190,
        "ceiling": 480,
    },
    {
        "charterer": "bodden-segler",
        "base": "Marina Breege",
        "name": "Kap Arkona",
        "manufacturer": "X-Yachts",
        "model": "X4³",
        "year_built": 2019,
        "length_m": 12.9,
        "beam_m": 3.95,
        "draft_m": 2.2,
        "displacement_kg": 9300,
        "sail_area_m2": 98,
        "engine_hp": 40,
        "cabins": 3,
        "berths": 6,
        "max_persons": 6,
        "heads": 2,
        "headroom_cm": 196,
        "max_berth_length_cm": 200,
        "character": ["sporty", "bluewater"],
        "required_license": 3,
        "required_experience_nm": 1500,
        "features": ["autopilot", "plotter", "radar", "sprayhood", "code0", "carbon_mast", "heating"],
        "description": "Performance-Cruiser mit Stahlrahmen und Carbonmast. Für erfahrene Crews, die schnell und sicher unterwegs sein wollen.",
        "min_days": 4,
        "cleaning_fee": 200,
        "deposit": 4000,
        "ref": 480,
        "floor": 280,
        "ceiling": 700,
    },
]

DEMO_CUSTOMER = {
    "email": "segler@example.com",
    "password": "segeln123",
    "full_name": "Sabine Segler",
    "license_level": 2,
    "experience_nm": 600,
    "height_cm": 188,
}
DEMO_ADMIN = {"email": "admin@sailbase.example", "password": "admin12345", "full_name": "Sailbase Admin"}
